branch-defaults:
  aws:
    environment: WEDx-dev6
  master:
    environment: null
    group_suffix: null
environment-defaults:
  WEDx-dev6:
    branch: null
    repository: null
global:
  application_name: wedx
  branch: null
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
